[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
summon_battle = "31PMrc54Z6aZ8YHbm47FugFKpzUc6PJ92vNJtinBUPxN"

[programs.localnet]
summon_battle = "31PMrc54Z6aZ8YHbm47FugFKpzUc6PJ92vNJtinBUPxN"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"

[hooks]
